% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={P1},
  pdfauthor={Heitor},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{P1}
\author{Heitor}
\date{2022-05-02}

\begin{document}
\maketitle

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#loading packages}
\FunctionTok{library}\NormalTok{(hnp)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'hnp' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Loading required package: MASS
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(lattice)}
\FunctionTok{library}\NormalTok{(multcomp)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'multcomp' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Loading required package: mvtnorm
\end{verbatim}

\begin{verbatim}
## Loading required package: survival
\end{verbatim}

\begin{verbatim}
## Warning: package 'survival' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Loading required package: TH.data
\end{verbatim}

\begin{verbatim}
## Warning: package 'TH.data' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'TH.data'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:MASS':
## 
##     geyser
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'tidyverse' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## -- Attaching packages --------------------------------------- tidyverse 1.3.1 --
\end{verbatim}

\begin{verbatim}
## v ggplot2 3.3.5     v purrr   0.3.4
## v tibble  3.1.6     v dplyr   1.0.8
## v tidyr   1.2.0     v stringr 1.4.0
## v readr   2.1.2     v forcats 0.5.1
\end{verbatim}

\begin{verbatim}
## Warning: package 'ggplot2' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'tibble' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'tidyr' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'readr' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'purrr' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'dplyr' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'stringr' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## Warning: package 'forcats' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
## x dplyr::filter() masks stats::filter()
## x dplyr::lag()    masks stats::lag()
## x dplyr::select() masks MASS::select()
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(gplots)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'gplots' was built under R version 4.1.3
\end{verbatim}

\begin{verbatim}
## 
## Attaching package: 'gplots'
\end{verbatim}

\begin{verbatim}
## The following object is masked from 'package:stats':
## 
##     lowess
\end{verbatim}

Questão 01

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df01 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
\FloatTok{76.2}\NormalTok{, }\FloatTok{80.6}\NormalTok{, }\FloatTok{67.6}\NormalTok{, }\FloatTok{79.4}\NormalTok{, }\FloatTok{83.4}\NormalTok{, }\FloatTok{87.2}\NormalTok{,}
\FloatTok{75.0}\NormalTok{, }\FloatTok{79.4}\NormalTok{, }\FloatTok{68.6}\NormalTok{, }\FloatTok{74.0}\NormalTok{, }\FloatTok{83.8}\NormalTok{, }\FloatTok{88.2}\NormalTok{,}
\FloatTok{80.4}\NormalTok{, }\FloatTok{69.8}\NormalTok{, }\FloatTok{76.0}\NormalTok{, }\FloatTok{64.8}\NormalTok{, }\FloatTok{79.0}\NormalTok{, }\FloatTok{66.0}\NormalTok{,}
\FloatTok{80.6}\NormalTok{, }\FloatTok{74.0}\NormalTok{, }\FloatTok{72.6}\NormalTok{, }\FloatTok{63.2}\NormalTok{, }\FloatTok{76.8}\NormalTok{, }\FloatTok{66.4}\NormalTok{,}
\FloatTok{82.2}\NormalTok{, }\FloatTok{71.6}\NormalTok{, }\FloatTok{72.6}\NormalTok{, }\FloatTok{64.4}\NormalTok{, }\FloatTok{78.4}\NormalTok{, }\FloatTok{66.6}\NormalTok{,}
\FloatTok{84.6}\NormalTok{, }\FloatTok{69.4}\NormalTok{, }\FloatTok{73.4}\NormalTok{, }\FloatTok{64.4}\NormalTok{, }\FloatTok{77.2}\NormalTok{, }\FloatTok{73.2}\NormalTok{,}
\FloatTok{69.6}\NormalTok{,}\FloatTok{73.0}\NormalTok{,  }\FloatTok{47.4}\NormalTok{ ,}\FloatTok{62.6}\NormalTok{, }\FloatTok{74.0}\NormalTok{, }\FloatTok{77.4}\NormalTok{,}
\FloatTok{62.6}\NormalTok{, }\FloatTok{89.2}\NormalTok{, }\FloatTok{52.2}\NormalTok{, }\FloatTok{79.4}\NormalTok{, }\FloatTok{73.4}\NormalTok{, }\FloatTok{95.4}\NormalTok{,}
\FloatTok{67.4}\NormalTok{, }\FloatTok{79.2}\NormalTok{, }\FloatTok{52.2}\NormalTok{, }\FloatTok{72.0}\NormalTok{, }\FloatTok{75.4}\NormalTok{, }\FloatTok{92.0}\NormalTok{,}
\FloatTok{93.0}\NormalTok{, }\FloatTok{81.4}\NormalTok{, }\FloatTok{82.0}\NormalTok{, }\FloatTok{78.4}\NormalTok{, }\FloatTok{91.4}\NormalTok{, }\FloatTok{92.2}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{A }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
\FloatTok{76.2}\NormalTok{, }\FloatTok{80.6}\NormalTok{,}
\FloatTok{75.0}\NormalTok{, }\FloatTok{79.4}\NormalTok{,}
\FloatTok{80.4}\NormalTok{, }\FloatTok{69.8}\NormalTok{,}
\FloatTok{80.6}\NormalTok{, }\FloatTok{74.0}\NormalTok{,}
\FloatTok{82.2}\NormalTok{, }\FloatTok{71.6}\NormalTok{,}
\FloatTok{84.6}\NormalTok{, }\FloatTok{69.4}\NormalTok{,}
\FloatTok{69.6}\NormalTok{, }\FloatTok{73.0}\NormalTok{,}
\FloatTok{62.6}\NormalTok{, }\FloatTok{89.2}\NormalTok{,}
\FloatTok{67.4}\NormalTok{, }\FloatTok{79.2}\NormalTok{,}
\FloatTok{93.0}\NormalTok{, }\FloatTok{81.4}\NormalTok{)}

\NormalTok{B }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{67.6}\NormalTok{, }\FloatTok{79.4}\NormalTok{,}
\FloatTok{68.6}\NormalTok{, }\FloatTok{74.0}\NormalTok{,}
\FloatTok{76.0}\NormalTok{, }\FloatTok{64.8}\NormalTok{,}
\FloatTok{72.6}\NormalTok{, }\FloatTok{63.2}\NormalTok{,}
\FloatTok{72.6}\NormalTok{, }\FloatTok{64.4}\NormalTok{,}
\FloatTok{73.4}\NormalTok{, }\FloatTok{64.4}\NormalTok{,}
\FloatTok{47.4}\NormalTok{ ,}\FloatTok{62.6}\NormalTok{,}
\FloatTok{52.2}\NormalTok{, }\FloatTok{79.4}\NormalTok{,}
\FloatTok{52.2}\NormalTok{, }\FloatTok{72.0}\NormalTok{,}
\FloatTok{82.0}\NormalTok{, }\FloatTok{78.4}\NormalTok{)}

\NormalTok{C }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
\FloatTok{83.4}\NormalTok{, }\FloatTok{87.2}\NormalTok{,}
\FloatTok{83.8}\NormalTok{, }\FloatTok{88.2}\NormalTok{,}
\FloatTok{79.0}\NormalTok{, }\FloatTok{66.0}\NormalTok{,}
\FloatTok{76.8}\NormalTok{, }\FloatTok{66.4}\NormalTok{,}
\FloatTok{78.4}\NormalTok{, }\FloatTok{66.6}\NormalTok{,}
\FloatTok{77.2}\NormalTok{, }\FloatTok{73.2}\NormalTok{,}
\FloatTok{74.0}\NormalTok{, }\FloatTok{77.4}\NormalTok{,}
\FloatTok{73.4}\NormalTok{, }\FloatTok{95.4}\NormalTok{,}
\FloatTok{75.4}\NormalTok{, }\FloatTok{92.0}\NormalTok{,}
\FloatTok{91.4}\NormalTok{, }\FloatTok{92.2}
\NormalTok{)}

\CommentTok{\#criando o dataframe com os dados}


\NormalTok{a }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{replicate}\NormalTok{(}\DecValTok{20}\NormalTok{,}\StringTok{"A"}\NormalTok{))}
\NormalTok{b }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{replicate}\NormalTok{(}\DecValTok{20}\NormalTok{,}\StringTok{"B"}\NormalTok{))}
\NormalTok{c }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{replicate}\NormalTok{(}\DecValTok{20}\NormalTok{,}\StringTok{"C"}\NormalTok{))}

\NormalTok{df01 }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\StringTok{"trat"} \OtherTok{=} \FunctionTok{c}\NormalTok{(a,b,c),}
                   \StringTok{"altura"} \OtherTok{=} \FunctionTok{c}\NormalTok{(A,B,C))}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\item
  Faça um possível croqui de instalação para um novo experimento com o
  mesmo número de tratamentos (variedades) e com cinco repetições; (0, 5
  pontos)
\item
  Calcule o número de repetições, a média, a variância e o desvio padrão
  das alturas para cada tratamento; (0, 25 × 4 pontos)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#numero repeticoes}
\NormalTok{n\_a }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(A)}
\NormalTok{n\_b }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(B)}
\NormalTok{n\_c }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(C)}

\CommentTok{\#media dos tratamentos}
\NormalTok{meda }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(A)}
\NormalTok{medb }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(B)}
\NormalTok{medc }\OtherTok{\textless{}{-}} \FunctionTok{mean}\NormalTok{(C)}

\FunctionTok{print}\NormalTok{(meda)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 76.96
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(medb)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 68.36
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(medc)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 79.87
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#variancia dos tratamentos}
\FunctionTok{print}\NormalTok{(}\FunctionTok{var}\NormalTok{(A))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 56.82779
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{var}\NormalTok{(B))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 92.70989
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{var}\NormalTok{(C))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 81.08326
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#desvio padrao dos tratamentos}
\FunctionTok{print}\NormalTok{(}\FunctionTok{sd}\NormalTok{(A))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 7.538421
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{sd}\NormalTok{(B))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.628598
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{sd}\NormalTok{(C))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 9.004625
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  Realize uma análise gráfica
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plotmeans}\NormalTok{(df01}\SpecialCharTok{$}\NormalTok{altura }\SpecialCharTok{\textasciitilde{}}\NormalTok{ df01}\SpecialCharTok{$}\NormalTok{trat, }\AttributeTok{xlab =} \StringTok{"Treatment"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Height(cm)"}\NormalTok{, }
          \AttributeTok{main =} \StringTok{"Mean Plot}\SpecialCharTok{\textbackslash{}n}\StringTok{with 95\% CI"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{p1_11833351_planexp_files/figure-latex/unnamed-chunk-5-1.pdf}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  Verifique se as pressuposições básicas do modelo foram atendidas e
  conclua considerando-se o nível de significância 5\%; (0, 5 × 2
  pontos)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#verificando se as variancias sao iguais}
\FunctionTok{var.test}\NormalTok{(A,B)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  A and B
## F = 0.61296, num df = 19, denom df = 19, p-value = 0.2948
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.2426184 1.5486224
## sample estimates:
## ratio of variances 
##          0.6129636
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var.test}\NormalTok{(B,C)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  B and C
## F = 1.1434, num df = 19, denom df = 19, p-value = 0.7733
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.4525682 2.8887219
## sample estimates:
## ratio of variances 
##           1.143391
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{var.test}\NormalTok{(A,C)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  F test to compare two variances
## 
## data:  A and C
## F = 0.70086, num df = 19, denom df = 19, p-value = 0.4457
## alternative hypothesis: true ratio of variances is not equal to 1
## 95 percent confidence interval:
##  0.2774078 1.7706813
## sample estimates:
## ratio of variances 
##          0.7008572
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#os tratamentos nao possuem variancias distintas}

\CommentTok{\#realizando o teste{-}t para os tres tratamentos}

\FunctionTok{t.test}\NormalTok{(A,B, }\AttributeTok{var.equal =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Two Sample t-test
## 
## data:  A and B
## t = 3.1451, df = 38, p-value = 0.003219
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##   3.064518 14.135482
## sample estimates:
## mean of x mean of y 
##     76.96     68.36
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(B,C, }\AttributeTok{var.equal =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Two Sample t-test
## 
## data:  B and C
## t = -3.9046, df = 38, p-value = 0.0003744
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -17.477555  -5.542445
## sample estimates:
## mean of x mean of y 
##     68.36     79.87
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{t.test}\NormalTok{(A,C, }\AttributeTok{var.equal =}\NormalTok{ T)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Two Sample t-test
## 
## data:  A and C
## t = -1.1082, df = 38, p-value = 0.2748
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -8.225934  2.405934
## sample estimates:
## mean of x mean of y 
##     76.96     79.87
\end{verbatim}

O teste t entre os trës tratamentos nos revela que: * tratamento A e B:
possuem médias distintas * Tratamento A e C: possuem médias distintas *
tratamento B e C: não possuem diferenças em suas médias estaticamente
significantes dados \(\alpha = 5%
\)

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{4}
\tightlist
\item
  Se as pressuposições básicas forem atendidas, faça a análise de
  variância e conclua considerando-se o nível de significância 5\%; (1,
  0 ponto)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{aov\_model }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(df01}\SpecialCharTok{$}\NormalTok{altura }\SpecialCharTok{\textasciitilde{}}\NormalTok{ df01}\SpecialCharTok{$}\NormalTok{trat)}
\FunctionTok{summary}\NormalTok{(aov\_model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             Df Sum Sq Mean Sq F value   Pr(>F)    
## df01$trat    2   1433   716.4   9.319 0.000315 ***
## Residuals   57   4382    76.9                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Considerando um nivel de significancia de 5\%, podemos concluir que
existe diferenca entre as alturas das tres especies de plantas, pois o
p-valor de 0.00031 e menor do que 5\%

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{5}
\tightlist
\item
  Se a continuidade da análise for recomendada (Quadro ANOVA), aplique o
  teste de comparações múltiplas de Tukey, apresente gráficos,
  interprete. (1, 0 ponto)
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tukey }\OtherTok{\textless{}{-}} \FunctionTok{TukeyHSD}\NormalTok{(aov\_model, }\StringTok{\textquotesingle{}df01$trat\textquotesingle{}}\NormalTok{, }\AttributeTok{conf.level =} \FloatTok{0.95}\NormalTok{)}
\NormalTok{tukey}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = df01$altura ~ df01$trat)
## 
## $`df01$trat`
##      diff        lwr       upr     p adj
## B-A -8.60 -15.272058 -1.927942 0.0082815
## C-A  2.91  -3.762058  9.582058 0.5490537
## C-B 11.51   4.837942 18.182058 0.0003247
\end{verbatim}

O teste Tukey, nos indica que existe diferenca significativa
considerando um alpha de 5\%, apenas entre as plantas A-B e C-B.

Isso pode ser melhor visualizado com o grafico family-wise comparison, a
seguir.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#tukey test representation}
\FunctionTok{plot}\NormalTok{(tukey, }\AttributeTok{las =} \DecValTok{1}\NormalTok{, }\AttributeTok{col =} \StringTok{\textquotesingle{}brown\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{p1_11833351_planexp_files/figure-latex/unnamed-chunk-9-1.pdf}
Como o intervalo de confianca entre A-C, contem o 0 nao podemos aformar
que existe diferenca entre as medias.

\#Questao 02

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Obtenha a soma de quadrados de tratamentos (Tabela da ANOVA) (0, 5
  pontos)
\end{enumerate}

Conforme a tabela anova acima, temos que: \(SS = 1433\)

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{1}
\tightlist
\item
  O quadrado médio do resíduo (Tabela da ANOVA) (0, 5 pontos)
\end{enumerate}

\(MQ_{res} = 76.9\)

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{2}
\tightlist
\item
  O valor p do teste F (Tabela da ANOVA) (0, 5 pontos)
\end{enumerate}

\(p-value = 0.000315\)

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\setcounter{enumi}{3}
\tightlist
\item
  A diferença mínima significativa (DMS) do teste de Tukey (0, 5 pontos)
\end{enumerate}

\#Questao 03

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{I1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{,}\DecValTok{4}\NormalTok{, }
\DecValTok{5}\NormalTok{, }
\DecValTok{6}\NormalTok{ ,}
\DecValTok{7}\NormalTok{ ,}
\DecValTok{8}\NormalTok{ ,}
\DecValTok{9}\NormalTok{ ,}
\DecValTok{10}\NormalTok{,}
\DecValTok{11}\NormalTok{,}
\DecValTok{12}\NormalTok{)}

\NormalTok{C1 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{0.265}\NormalTok{,}
\FloatTok{0.265}\NormalTok{,}
\FloatTok{0.266}\NormalTok{,}
\FloatTok{0.267}\NormalTok{,}
\FloatTok{0.267}\NormalTok{,}
\FloatTok{0.265}\NormalTok{,}
\FloatTok{0.267}\NormalTok{,}
\FloatTok{0.267}\NormalTok{,}
\FloatTok{0.265}\NormalTok{,}
\FloatTok{0.268}\NormalTok{,}
\FloatTok{0.268}\NormalTok{,}
\FloatTok{0.265}\NormalTok{ )}

\NormalTok{C2 }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FloatTok{0.264}\NormalTok{,}
\FloatTok{0.265}\NormalTok{,}
\FloatTok{0.264}\NormalTok{,}
\FloatTok{0.266}\NormalTok{,}
\FloatTok{0.267}\NormalTok{,}
\FloatTok{0.268}\NormalTok{,}
\FloatTok{0.264}\NormalTok{,}
\FloatTok{0.265}\NormalTok{,}
\FloatTok{0.265}\NormalTok{,}
\FloatTok{0.267}\NormalTok{,}
\FloatTok{0.268}\NormalTok{,}
\FloatTok{0.269}
\NormalTok{)}
\CommentTok{\#dataframe 03}

\NormalTok{a }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{replicate}\NormalTok{(}\DecValTok{12}\NormalTok{,}\StringTok{"I1"}\NormalTok{))}
\NormalTok{b }\OtherTok{\textless{}{-}}\FunctionTok{c}\NormalTok{(}\FunctionTok{replicate}\NormalTok{(}\DecValTok{12}\NormalTok{,}\StringTok{"C1"}\NormalTok{))}
\NormalTok{c }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\FunctionTok{replicate}\NormalTok{(}\DecValTok{12}\NormalTok{, }\StringTok{"C2"}\NormalTok{))}


\NormalTok{df03 }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(}\StringTok{"trat"} \OtherTok{=} \FunctionTok{c}\NormalTok{(b,c),}
                   \StringTok{"measure"} \OtherTok{=} \FunctionTok{c}\NormalTok{(C1,C2))}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\tightlist
\item
  Existe uma diferença significativa entre as médias das medições dos
  calibradores? Use α = 0, 05.(1, 0 ponto). Interprete o resultado.
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{plotmeans}\NormalTok{(df03}\SpecialCharTok{$}\NormalTok{measure }\SpecialCharTok{\textasciitilde{}}\NormalTok{ df03}\SpecialCharTok{$}\NormalTok{trat, }\AttributeTok{xlab =} \StringTok{"Calibrador"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Medida"}\NormalTok{, }
          \AttributeTok{main =} \StringTok{"Mean Plot}\SpecialCharTok{\textbackslash{}n}\StringTok{with 95\% CI"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{p1_11833351_planexp_files/figure-latex/unnamed-chunk-11-1.pdf}
Teste anova para verificar a existencia na diferenca de medias

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df03\_aov }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(df03}\SpecialCharTok{$}\NormalTok{measure }\SpecialCharTok{\textasciitilde{}}\NormalTok{ df03}\SpecialCharTok{$}\NormalTok{trat)}
\FunctionTok{summary}\NormalTok{(df03\_aov)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             Df    Sum Sq   Mean Sq F value Pr(>F)
## df03$trat    1 3.800e-07 3.750e-07   0.164  0.689
## Residuals   22 5.025e-05 2.284e-06
\end{verbatim}

\begin{enumerate}
\def\labelenumi{\alph{enumi})}
\item
  Não existe diferença na média dos calibradores
\item
  O valor - p para o Teste F foi de \(p-value = 0,68\) para
  \(\alpha = 5{\%}\)
\item
  Construa um intervalo de confiança para as médias
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(multcompView)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: package 'multcompView' was built under R version 4.1.3
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{model }\OtherTok{=} \FunctionTok{lm}\NormalTok{(df03}\SpecialCharTok{$}\NormalTok{measure }\SpecialCharTok{\textasciitilde{}}\NormalTok{ df03}\SpecialCharTok{$}\NormalTok{trat)}
\NormalTok{anova}\OtherTok{=}\FunctionTok{aov}\NormalTok{(model)}

\FunctionTok{summary}\NormalTok{(anova)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##             Df    Sum Sq   Mean Sq F value Pr(>F)
## df03$trat    1 3.800e-07 3.750e-07   0.164  0.689
## Residuals   22 5.025e-05 2.284e-06
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#tukey test }

\NormalTok{tukey }\OtherTok{\textless{}{-}} \FunctionTok{TukeyHSD}\NormalTok{(anova, }\StringTok{\textquotesingle{}df03$trat\textquotesingle{}}\NormalTok{, }\AttributeTok{conf.level =} \FloatTok{0.95}\NormalTok{)}
\NormalTok{tukey}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = model)
## 
## $`df03$trat`
##           diff          lwr         upr     p adj
## C2-C1 -0.00025 -0.001529568 0.001029568 0.6892509
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#tukey test representation}
\FunctionTok{plot}\NormalTok{(tukey, }\AttributeTok{las =} \DecValTok{1}\NormalTok{, }\AttributeTok{col =} \StringTok{\textquotesingle{}brown\textquotesingle{}}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{p1_11833351_planexp_files/figure-latex/unnamed-chunk-13-1.pdf}
O intervalo de confiança acima nos indica que: 1. Temos 95\% de
confoança de que o real valor da diferença entre as médias do Calibrador
C1 e do Calibrador C2, reside dentro do intervalo {[}-0.0015, 0.0010{]}.
Como esse intervalo contem o zero, nao podemos rejeitar \(H_0\): a
diferenca entre as medias e 0.

\end{document}
